defaults:
  - model_summary
  - rich_progress_bar
  - config_lr_scheduler
  - learning_rate_monitor
  - model_checkpoint
  - peak_memory
  - _self_

model_summary:
  max_depth: -1

model_checkpoint:
  monitor: val/loss
  mode: min
