# @package _global_

defaults:
  - _self_
  - data: Waterdrop # choose datamodule with `test_dataloader()` for evaluation
  - model: null
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: waterdrop_physics

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: logs/train/runs/2025-01-11_21-57-30/waterdrop/gj5rf4ki/checkpoints/epoch=9-step=149700.ckpt
